// Logo paths
export const logos = {
  wharton: '/images/logos/wharton-logo.svg',
  avalanche: '/images/logos/avalanche-fusion.jpeg',
  lowercarbon: '/images/logos/lowercarbon-capital.jpeg',
  noteefy: '/images/logos/noteefy.jpeg',
  flowbo: '/images/logos/flowbo.jpeg',
  venrex: '/images/logos/venrex.jpeg',
  rogo: '/images/logos/rogo.jpeg',
  juniver: '/images/logos/juniver.jpeg',
  sownToGrow: '/images/logos/sowntogrow.jpeg',
  auterion: '/images/logos/auterion.jpeg',
  globalizationPartners: '/images/logos/globalizationpartners.jpeg',
  embeddedVentures: '/images/logos/embeddedventures.jpeg',
  redpoint: '/images/logos/redpoint.jpeg',
  aminoCapital: '/images/logos/aminocapital.jpeg',
  moonhubAi: '/images/logos/moonhubai.jpeg',
  zoo: '/images/logos/zoo.jpg',
  oursky: '/images/logos/oursky.jpg',
  lumen: '/images/logos/lumen.jpg',
  a16z: '/images/logos/a16z.jpg',
  autoblocksAi: '/images/logos/autoblocks-ai.png',
  deepmind: '/images/logos/deepmind.png',
  normAi: '/images/logos/norm-ai.jpg',
  capsule: '/images/logos/capsule.png',
  healthie: '/images/logos/healthie.png',
  aavrani: '/images/logos/aavrani.jpeg',
  emergenceCapital: '/images/logos/emergencecapital.jpeg',
  bastion: '/images/logos/bastion.jpeg',
  stripe: '/images/logos/stripe.jpeg',
  portal: '/images/logos/portal.jpeg',
  bankless: '/images/logos/bankless.svg',
  coinbase: '/images/logos/coinbase.jpeg',
  m13: '/images/logos/m13.jpeg',
  octave: '/images/logos/octave.jpg'
} as const;

// Avatar paths
export const avatars = {
  robertBorghese: '/images/avatars/robert-borghese.jpeg',
  brianRiordan: '/images/avatars/brian-riordan.jpeg',
  shawnXu: '/images/avatars/shawn-xu.jpeg',
  jakeGordon: '/images/avatars/jake-gordon.jpeg',
  danielKang: '/images/avatars/daniel-kang.jpeg',
  ianGoldberg: '/images/avatars/ian-goldberg.jpeg',
  hannahFrankl: '/images/avatars/hannah-frankl.jpeg',
  allieDiPietro: '/images/avatars/allie-dipietro.jpeg',
  jacquelineKeene: '/images/avatars/jacqueline-keene.jpeg',
  filipposLetsas: '/images/avatars/filippos-letsas.jpeg',
  nicoleSahin: '/images/avatars/nicole-sahin.jpeg',
  jennaBryant: '/images/avatars/jenna-bryant.jpeg',
  urvashipBarooah: '/images/avatars/urvashi-barooah.jpeg',
  sueXu: '/images/avatars/sue-xu.jpeg',
  nancyXu: '/images/avatars/nancy-xu.jpeg',
  sandeepAcharya: '/images/avatars/sandeep-acharya.jpg',
  jordanNoone: '/images/avatars/jordan-noone.jpg',
  danielRoelker: '/images/avatars/daniel-roelker.jpg',
  phillipJohnston: '/images/avatars/phillip-johnston.jpg',
  jamesDaCosta: '/images/avatars/james-da-costa.jpg',
  gabrielStengel: '/images/avatars/gabriel-stengel.jpg',
  haroonChoudery: '/images/avatars/haroon-choudery.jpg',
  loganKilpatrick: '/images/avatars/logan-kilpatrick.jpg',
  johnNay: '/images/avatars/john-nay.jpg',
  ericKinariwala: '/images/avatars/eric-kinariwala.jpg',
  cavanKlinsky: '/images/avatars/cavan-klinsky.jpg',
  justinSilver: '/images/avatars/justin-silver.jpeg',
  gordonRitter: '/images/avatars/gordon-ritter.jpeg',
  nassimEddequiouaq: '/images/avatars/nassim-eddequiouaq.jpeg',
  nickKrakoff: '/images/avatars/nick-krakoff.jpeg',
  ramiShahatit: '/images/avatars/rami-shahatit.jpeg',
  ejaazAhamadeen: '/images/avatars/ejaaz-ahamadeen.jpeg',
  andrewF: '/images/avatars/andrew-f.jpeg',
  markGrace: '/images/avatars/mark-grace.jpeg'
} as const; 