// Logo paths
export const logos = {
  a16z: '/images/logos/a16z.png',
  aavrani: '/images/logos/aavrani.png',
  aminocapital: '/images/logos/aminocapital.png',
  autoblocksAi: '/images/logos/autoblocks-ai.png',
  auterion: '/images/logos/auterion.png',
  avalanche: '/images/logos/avalanche.png',
  avalancheFusion: '/images/logos/avalanche-fusion.jpeg',
  bankless: '/images/logos/bankless.png',
  bastion: '/images/logos/bastion.jpeg',
  capsule: '/images/logos/capsule.png',
  coinbase: '/images/logos/coinbase.png',
  deepmind: '/images/logos/deepmind.png',
  embeddedVentures: '/images/logos/embeddedventures.png',
  emergenceCapital: '/images/logos/emergencecapital.jpeg',
  flowbo: '/images/logos/flowbo.png',
  globalizationPartners: '/images/logos/globalizationpartners.png',
  healthie: '/images/logos/healthie.png',
  juniver: '/images/logos/juniver.png',
  lowercarbonCapital: '/images/logos/lowercarboncapital.jpeg',
  lumen: '/images/logos/lumen.jpg',
  m13: '/images/logos/m13.jpeg',
  moonhubAi: '/images/logos/moonhubai.png',
  normAi: '/images/logos/norm-ai.png',
  noteefy: '/images/logos/noteefy.png',
  octave: '/images/logos/octave.png',
  octaveWhite: '/images/logos/octave-white.png',
  oursky: '/images/logos/oursky.png',
  portal: '/images/logos/portal.png',
  redpoint: '/images/logos/redpoint.png',
  rogo: '/images/logos/rogo.png',
  sowntogrow: '/images/logos/sowntogrow.png',
  starcloud: '/images/logos/starcloud.png',
  stripe: '/images/logos/stripe.png',
  symptoguard: '/images/logos/symptoguard.png',
  venrex: '/images/logos/venrex.png',
  wharton: '/images/logos/wharton-logo.svg',
  zoo: '/images/logos/zoo.png',
} as const;

// Avatar paths
export const avatars = {
  robertBorghese: '/images/avatars/robert-borghese.jpeg',
  brianRiordan: '/images/avatars/brian-riordan.jpeg',
  shawnXu: '/images/avatars/shawn-xu.jpeg',
  jakeGordon: '/images/avatars/jake-gordon.jpeg',
  danielKang: '/images/avatars/daniel-kang.jpeg',
  ianGoldberg: '/images/avatars/ian-goldberg.jpeg',
  hannahFrankl: '/images/avatars/hannah-frankl.jpeg',
  allieDiPietro: '/images/avatars/allie-dipietro.jpeg',
  jacquelineKeene: '/images/avatars/jacqueline-keene.jpeg',
  filipposLetsas: '/images/avatars/filippos-letsas.jpeg',
  nicoleSahin: '/images/avatars/nicole-sahin.jpeg',
  jennaBryant: '/images/avatars/jenna-bryant.jpeg',
  urvashipBarooah: '/images/avatars/urvashi-barooah.jpeg',
  sueXu: '/images/avatars/sue-xu.jpeg',
  nancyXu: '/images/avatars/nancy-xu.jpeg',
  sandeepAcharya: '/images/avatars/sandeep-acharya.png',
  jordanNoone: '/images/avatars/jordan-noone.jpg',
  danielRoelker: '/images/avatars/daniel-roelker.jpg',
  phillipJohnston: '/images/avatars/phillip-johnston.jpg',
  jamesDaCosta: '/images/avatars/james-da-costa.jpg',
  gabrielStengel: '/images/avatars/gabriel-stengel.jpg',
  haroonChoudery: '/images/avatars/haroon-choudery.jpg',
  loganKilpatrick: '/images/avatars/logan-kilpatrick.jpg',
  johnNay: '/images/avatars/john-nay.jpg',
  ericKinariwala: '/images/avatars/eric-kinariwala.jpg',
  cavanKlinsky: '/images/avatars/cavan-klinsky.jpg',
  justinSilver: '/images/avatars/justin-silver.jpeg',
  gordonRitter: '/images/avatars/gordon-ritter2.jpeg',
  nassimEddequiouaq: '/images/avatars/nassim-eddequiouaq.jpeg',
  nickKrakoff: '/images/avatars/nick-krakoff.jpeg',
  ramiShahatit: '/images/avatars/rami-shahatit.jpeg',
  ejaazAhamadeen: '/images/avatars/ejaaz-ahamadeen.jpeg',
  andrewF: '/images/avatars/andrew-f.jpeg',
  markGrace: '/images/avatars/mark-grace.jpeg'
} as const; 